# Generated by Django 5.1.6 on 2025-02-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='pdf_file',
            field=models.FileField(default='home/pdfs/default.pdf', upload_to='home/pdfs/'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
